typography_spectrum: 0.9713788775261492
color:
  brandStrength: 0.03940755897201598
  lightness: 0.6166713149286807
  saturation: 0.5475304753053933
  rhythmicContrast: 0.8807818333152682
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.5705450049135834
author:
  name: Toby Statham
  email: toby@wutek.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/99000fa3-274f-4b03-a678-8ca9d0f3694b.png
name: wutek
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d8d3e1d7-1e50-4aad-99ab-8ad4144a9194.ico
title: Get Better
description: 'Better solutions, better Apps, better Add-ins.'
